# Generated by Django 3.1.3 on 2021-01-15 22:08

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('organization', models.CharField(max_length=50, verbose_name='Организация')),
                ('inn', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Введите корректный ИНН', regex='^[0-9]{9}$')], verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Введите корректный КПП', regex='^[0-9]{11}$')], verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Введите корректный ОГРН', regex='^[0-9]{10}$')], verbose_name='ОГРН')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип организации')),
                ('text_org', models.TextField(verbose_name='Описание организации')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на сайт организации')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organization',
            },
        ),
    ]
