# Generated by Django 3.1.3 on 2021-01-16 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_site', '0002_auto_20210116_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='salary',
            field=models.CharField(default='0', max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='Введите корректную зарплату', regex='^[0-9]{0, 9}')], verbose_name='Заработная плата'),
        ),
    ]
