# Generated by Django 3.1.3 on 2020-11-11 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
        ('user', '0001_initial'),
        ('hh_site', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий для вопроса',
                'verbose_name_plural': 'Комментарии для вопросов',
                'ordering': ['quest'],
            },
        ),
        migrations.CreateModel(
            name='CommentOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий для организации',
                'verbose_name_plural': 'Комментарии для оорганизаций',
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.answer', verbose_name='Ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий для ответа',
                'verbose_name_plural': 'Комментарии для ответов',
                'ordering': ['answer'],
            },
        ),
        migrations.CreateModel(
            name='CommentAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_site.ad', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий для объявлений',
                'verbose_name_plural': 'Комментарии для объявлений',
                'ordering': ['ad'],
            },
        ),
    ]
